const express = require('express');
const fs = require('fs').promises;
const path = require('path');
const sharp = require('sharp'); // For image generation
const app = express();
const PORT = 3000;

// Enable CORS for local development
app.use((req, res, next) => {
    res.header('Access-Control-Allow-Origin', '*');
    res.header('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Accept');
    next();
});

// Serve static files
app.use(express.static('.'));

// Image generation cache
const imageCache = new Map();

// Generate a sample image using Sharp
async function generateSampleImage(text, bgColor, width = 300, height = 200) {
    const cacheKey = `${text}-${bgColor}-${width}x${height}`;
    
    if (imageCache.has(cacheKey)) {
        return imageCache.get(cacheKey);
    }

    try {
        // Create SVG for the image
        const svg = `
            <svg width="${width}" height="${height}" xmlns="http://www.w3.org/2000/svg">
                <defs>
                    <linearGradient id="grad" x1="0%" y1="0%" x2="100%" y2="100%">
                        <stop offset="0%" style="stop-color:${bgColor};stop-opacity:1" />
                        <stop offset="100%" style="stop-color:${adjustBrightness(bgColor, -30)};stop-opacity:1" />
                    </linearGradient>
                </defs>
                <rect width="100%" height="100%" fill="url(#grad)" stroke="white" stroke-width="2"/>
                <text x="50%" y="45%" text-anchor="middle" fill="white" font-family="Arial, sans-serif" font-size="20" font-weight="bold">${text}</text>
                <text x="50%" y="65%" text-anchor="middle" fill="rgba(255,255,255,0.8)" font-family="Arial, sans-serif" font-size="12">Generated by Server</text>
            </svg>
        `;

        const imageBuffer = await sharp(Buffer.from(svg))
            .png()
            .toBuffer();

        imageCache.set(cacheKey, imageBuffer);
        return imageBuffer;
    } catch (error) {
        console.error('Error generating image:', error);
        throw error;
    }
}

function adjustBrightness(hex, percent) {
    const num = parseInt(hex.replace("#", ""), 16);
    const amt = Math.round(2.55 * percent);
    const R = (num >> 16) + amt;
    const G = (num >> 8 & 0x00FF) + amt;
    const B = (num & 0x0000FF) + amt;
    return "#" + (0x1000000 + (R < 255 ? R < 1 ? 0 : R : 255) * 0x10000 +
        (G < 255 ? G < 1 ? 0 : G : 255) * 0x100 +
        (B < 255 ? B < 1 ? 0 : B : 255)).toString(16).slice(1);
}

// API endpoint to scan for files asynchronously
app.get('/api/files', async (req, res) => {
    try {
        const { offset = 0, limit = 50 } = req.query;
        const startOffset = parseInt(offset);
        const chunkLimit = parseInt(limit);
        
        console.log(`📁 Scanning files: offset=${startOffset}, limit=${chunkLimit}`);
        
        // Simulate async file scanning with actual file system operations
        const imageDir = path.join(__dirname, 'images');
        let files = [];
        
        try {
            // Try to read actual image files
            const actualFiles = await fs.readdir(imageDir, { withFileTypes: true });
            const imageFiles = actualFiles
                .filter(file => file.isFile() && /\.(jpg|jpeg|png|gif|webp)$/i.test(file.name))
                .map(file => ({
                    name: file.name,
                    fullPath: `/api/image/real/${file.name}`,
                    category: 'real',
                    type: 'file'
                }));
            
            files.push(...imageFiles);
            console.log(`📸 Found ${imageFiles.length} real image files`);
        } catch (err) {
            console.log('📁 No images directory found, using generated samples');
        }
        
        // Generate sample images to fill the request
        const sampleImages = [
            { text: 'Blue Sample', color: '#4299e1', category: 'background' },
            { text: 'Green Sample', color: '#38a169', category: 'background' },
            { text: 'Purple Sample', color: '#805ad5', category: 'background' },
            { text: 'Red Sample', color: '#e53e3e', category: 'background' },
            { text: 'Orange Sample', color: '#d69e2e', category: 'background' },
            { text: 'Teal Sample', color: '#3182ce', category: 'background' },
            { text: 'Violet Sample', color: '#6b46c1', category: 'background' },
            { text: 'Emerald Sample', color: '#2f855a', category: 'background' },
            { text: 'Crimson Sample', color: '#c53030', category: 'background' },
            { text: 'Gold Sample', color: '#b7791f', category: 'background' },
            { text: 'Logo Design', color: '#1e40af', category: 'logo' },
            { text: 'Icon Set', color: '#7c3aed', category: 'icon' },
            { text: 'Photo Sample', color: '#059669', category: 'photo' },
            { text: 'Banner', color: '#dc2626', category: 'banner' },
            { text: 'Header Image', color: '#ea580c', category: 'header' }
        ];
        
        // Generate enough samples to fulfill requests
        for (let i = 0; i < 200; i++) {
            const sample = sampleImages[i % sampleImages.length];
            const index = i + 1;
            files.push({
                name: `${sample.text.toLowerCase().replace(' ', '-')}-${String(index).padStart(3, '0')}.png`,
                fullPath: `/api/image/generated/${encodeURIComponent(sample.text)}/${sample.color.replace('#', '')}/${index}`,
                category: sample.category,
                type: 'generated'
            });
        }
        
        // Return the requested chunk
        const chunk = files.slice(startOffset, startOffset + chunkLimit);
        
        res.json({
            files: chunk,
            total: files.length,
            offset: startOffset,
            limit: chunkLimit,
            hasMore: startOffset + chunkLimit < files.length
        });
        
        console.log(`📦 Returned ${chunk.length} files (${startOffset}-${startOffset + chunkLimit})`);
        
    } catch (error) {
        console.error('❌ Error scanning files:', error);
        res.status(500).json({ error: 'Failed to scan files' });
    }
});

// Serve generated images
app.get('/api/image/generated/:text/:color/:index', async (req, res) => {
    try {
        const { text, color, index } = req.params;
        const decodedText = decodeURIComponent(text);
        const fullColor = `#${color}`;
        
        console.log(`🎨 Generating image: ${decodedText} (${fullColor})`);
        
        const imageBuffer = await generateSampleImage(decodedText, fullColor);
        
        res.setHeader('Content-Type', 'image/png');
        res.setHeader('Cache-Control', 'public, max-age=3600'); // Cache for 1 hour
        res.send(imageBuffer);
        
    } catch (error) {
        console.error('❌ Error generating image:', error);
        res.status(500).send('Error generating image');
    }
});

// Serve real image files
app.get('/api/image/real/:filename', async (req, res) => {
    try {
        const { filename } = req.params;
        const imagePath = path.join(__dirname, 'images', filename);
        
        console.log(`📸 Serving real image: ${filename}`);
        
        const imageBuffer = await fs.readFile(imagePath);
        const ext = path.extname(filename).toLowerCase();
        
        let contentType = 'image/png';
        if (ext === '.jpg' || ext === '.jpeg') contentType = 'image/jpeg';
        else if (ext === '.gif') contentType = 'image/gif';
        else if (ext === '.webp') contentType = 'image/webp';
        
        res.setHeader('Content-Type', contentType);
        res.setHeader('Cache-Control', 'public, max-age=3600');
        res.send(imageBuffer);
        
    } catch (error) {
        console.error('❌ Error serving real image:', error);
        res.status(404).send('Image not found');
    }
});

// Health check endpoint
app.get('/api/health', (req, res) => {
    res.json({ 
        status: 'OK', 
        message: 'Image server running',
        port: PORT,
        cacheSize: imageCache.size
    });
});

// Start server
app.listen(PORT, () => {
    console.log(`🚀 Image Server running at http://localhost:${PORT}`);
    console.log(`📁 Serving files from: ${__dirname}`);
    console.log(`🎨 Image generation: Enabled with Sharp`);
    console.log(`🔗 API endpoints:`);
    console.log(`   GET /api/files?offset=0&limit=50 - Get file list`);
    console.log(`   GET /api/image/generated/{text}/{color}/{index} - Generated images`);
    console.log(`   GET /api/image/real/{filename} - Real image files`);
    console.log(`   GET /api/health - Server status`);
});

module.exports = app;