// Component discovery data for web IDE
// This file is generated by running: node tools/component-discovery.js

window.WB_DISCOVERY_DATA = {
    "symbolTable": [
        ["wb-button", {"name": "wb-button", "type": "custom-element", "component": "wb-button", "webComponent": true}],
        ["wb-table", {"name": "wb-table", "type": "custom-element", "component": "wb-table", "webComponent": true}],
        ["wb-select", {"name": "wb-select", "type": "custom-element", "component": "wb-select", "webComponent": true}],
        ["wb-log-error", {"name": "wb-log-error", "type": "custom-element", "component": "wb-log-error", "webComponent": true}],
        ["wb-modal", {"name": "wb-modal", "type": "custom-element", "component": "wb-modal", "webComponent": true}],
        ["wb-toggle", {"name": "wb-toggle", "type": "custom-element", "component": "wb-toggle", "webComponent": true}],
        ["wb-status", {"name": "wb-status", "type": "custom-element", "component": "wb-status", "webComponent": true}],
        ["wb-nav", {"name": "wb-nav", "type": "custom-element", "component": "wb-nav", "webComponent": true}],
        ["wb-card", {"name": "wb-card", "type": "custom-element", "component": "wb-card", "webComponent": true}],
        ["wb-color-picker", {"name": "wb-color-picker", "type": "custom-element", "component": "wb-color-picker", "webComponent": true}],
        ["wb-footer", {"name": "wb-footer", "type": "custom-element", "component": "wb-footer", "webComponent": true}],
        ["wb-event-log", {"name": "wb-event-log", "type": "custom-element", "component": "wb-event-log", "webComponent": true}],
        ["control-panel", {"name": "control-panel", "type": "custom-element", "component": "control-panel", "webComponent": true}],
        ["color-bar", {"name": "color-bar", "type": "custom-element", "component": "color-bar", "webComponent": true}],
        ["WBComponentUtils", {"name": "WBComponentUtils", "type": "class", "component": "wb-component-utils", "webComponent": false}],
        ["WBButton", {"name": "WBButton", "type": "class", "component": "wb-button", "webComponent": false}],
        ["WBTable", {"name": "WBTable", "type": "class", "component": "wb-table", "webComponent": false}],
        ["WBSelect", {"name": "WBSelect", "type": "class", "component": "wb-select", "webComponent": false}],
        ["WBModal", {"name": "WBModal", "type": "class", "component": "wb-modal", "webComponent": false}],
        ["WBToggle", {"name": "WBToggle", "type": "class", "component": "wb-toggle", "webComponent": false}],
        ["WBStatus", {"name": "WBStatus", "type": "class", "component": "wb-status", "webComponent": false}],
        ["WBNav", {"name": "WBNav", "type": "class", "component": "wb-nav", "webComponent": false}],
        ["WBCard", {"name": "WBCard", "type": "class", "component": "wb-card", "webComponent": false}],
        ["WBColorPicker", {"name": "WBColorPicker", "type": "class", "component": "wb-color-picker", "webComponent": false}],
        ["WBFooter", {"name": "WBFooter", "type": "class", "component": "wb-footer", "webComponent": false}],
        ["WBEventLog", {"name": "WBEventLog", "type": "class", "component": "wb-event-log", "webComponent": false}],
        ["loadCSS", {"name": "loadCSS", "type": "function", "component": "wb-component-utils", "webComponent": false}],
        ["generateId", {"name": "generateId", "type": "function", "component": "wb-component-utils", "webComponent": false}],
        ["getPath", {"name": "getPath", "type": "function", "component": "wb-component-utils", "webComponent": false}],
        ["loadConfig", {"name": "loadConfig", "type": "function", "component": "wb-component-utils", "webComponent": false}]
    ],
    "componentRegistry": [
        {"name": "wb-button", "type": "web-component", "status": "complete", "customElement": "wb-button"},
        {"name": "wb-table", "type": "web-component", "status": "complete", "customElement": "wb-table"},
        {"name": "wb-select", "type": "web-component", "status": "complete", "customElement": "wb-select"},
        {"name": "wb-log-error", "type": "web-component", "status": "complete", "customElement": "wb-log-error"},
        {"name": "wb-modal", "type": "web-component", "status": "complete", "customElement": "wb-modal"},
        {"name": "wb-toggle", "type": "web-component", "status": "complete", "customElement": "wb-toggle"},
        {"name": "wb-status", "type": "web-component", "status": "complete", "customElement": "wb-status"},
        {"name": "wb-nav", "type": "web-component", "status": "complete", "customElement": "wb-nav"},
        {"name": "wb-card", "type": "web-component", "status": "complete", "customElement": "wb-card"},
        {"name": "wb-color-picker", "type": "web-component", "status": "complete", "customElement": "wb-color-picker"},
        {"name": "wb-footer", "type": "web-component", "status": "complete", "customElement": "wb-footer"},
        {"name": "wb-event-log", "type": "web-component", "status": "complete", "customElement": "wb-event-log"},
        {"name": "control-panel", "type": "web-component", "status": "complete", "customElement": "control-panel"},
        {"name": "color-bar", "type": "web-component", "status": "complete", "customElement": "color-bar"},
        {"name": "wb-input", "type": "legacy", "status": "broken", "issues": ["Input elements not functional"]},
        {"name": "control-panel-new", "type": "legacy", "status": "broken", "issues": ["JSON parsing errors"]},
        {"name": "change-text", "type": "legacy", "status": "broken", "issues": ["Edit mode not working"]},
        {"name": "image-insert", "type": "legacy", "status": "broken", "issues": ["Insert function broken"]},
        {"name": "wb-viewport", "type": "legacy", "status": "complete", "issues": ["Content darker in small viewports"]},
        {"name": "wb-component-utils", "type": "utility", "status": "complete"},
        {"name": "wb-slider", "type": "legacy", "status": "complete"},
        {"name": "wb-hero", "type": "legacy", "status": "complete"},
        {"name": "wb-header", "type": "legacy", "status": "complete"}
    ],
    "metadata": {
        "totalComponents": 23,
        "webComponents": 14,
        "legacyComponents": 9,
        "brokenComponents": 4,
        "scanTime": new Date().toISOString()
    }
};

console.log('🔍 WB Component Discovery Data loaded:', window.WB_DISCOVERY_DATA.metadata);